version: '3.8'

services:
  reg_service_postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: registration_service
      POSTGRES_USER: registration_service
      POSTGRES_PASSWORD: registration_service
    ports:
      - "6543:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: